In [1]:
import pandas as pd

df =pd.read_csv("C:/Users/wodyd/Desktop/학원수업/seoul_park.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      1086 non-null   object
 1   공휴일     1086 non-null   object
 2   날씨      946 non-null    object
 3   유료합계    1086 non-null   object
 4   어른      1086 non-null   object
 5   청소년     1081 non-null   object
 6   어린이     1086 non-null   object
 7   외국인     1086 non-null   object
 8   단체      1086 non-null   object
 9   무료합계    1086 non-null   object
 10  총계      1086 non-null   object
dtypes: object(11)
memory usage: 93.5+ KB

           날짜 공휴일     날씨   유료합계     어른  청소년  어린이  외국인   단체   무료합계     총계
0  2016-01-01   O  구름 조금  3,359  2,799  141  419   47    0  1,023  4,382
1  2016-01-02   O  구름 많음  5,173  4,370  203  600  100  111  2,092  7,265
2  2016-01-03   O  구름 많음  3,008  2,571  128  309   91    0  1,549  4,557
3  2016-01-04   X  구름 많음    890    602  NaN  235   51  223    800  1,690
4  2016-01-05   X  구름 많음    416    319   35   62   43   47    840  1,256

In [2]:
df['날씨']
df['날씨'].value_counts()

날씨
구름 많음    277
구름 조금    236
맑음       222
비        101
흐림       100
눈          6
눈/비        4
Name: count, dtype: int64

In [3]:
df.isnull().sum()

날짜        0
공휴일       0
날씨      140
유료합계      0
어른        0
청소년       5
어린이       0
외국인       0
단체        0
무료합계      0
총계        0
dtype: int64

In [4]:
df.describe()

,날짜,공휴일,날씨,유료합계,어른,청소년,어린이,외국인,단체,무료합계,총계
count,1086,1086,946,1086,1086,1081,1086,1086,1086,1086,1086
unique,1086,2,7,996,941,474,603,247,522,906,1012
top,2016-01-01,X,구름 많음,213,198,14,10,13,0,837,996
freq,1,731,277,5,4,17,11,22,351,5,3

In [ ]:
df['날짜'] = pd.to_datetime(df['날짜'])
df['날씨']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1086 entries, 0 to 1085
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      1086 non-null   datetime64[ns]
 1   공휴일     1086 non-null   object
 2   날씨      946 non-null    object
 3   유료합계    1086 non-null   object
 4   어른      1086 non-null   object
 5   청소년     1081 non-null   object
 6   어린이     1086 non-null   object
 7   외국인     1086 non-null   object
 8   단체      1086 non-null   object
 9   무료합계    1086 non-null   object
 10  총계      1086 non-null   object
dtypes: datetime64[ns](1), object(10)
memory usage: 93.5+ KB