# 파일 불러오기 (엑셀->CSV)

In [2]:
import pandas as pd
import numpy as np
import glob
import os

## 1. 주민등록인구 파일 불러오기

In [6]:
people_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\고령화율 데이터"
people_files = glob.glob(os.path.join(people_path, "*.xlsx"))

print(f"현재 파일 수: {len(people_files)}")
people_files

현재 파일 수: 6

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_10~11.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_12~14.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_15~16.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_17~19.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_20~22.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\고령화율 데이터\\행정구역_시군구_별_주민등록인구_23~24.xlsx']

### 1. 주민등록인구 파일 합치기

In [12]:
people_list = []
for f in people_files:
    df = pd.read_excel(f)
    people_list.append(df)

people_raw = pd.concat(people_list, ignore_index=True)
people_raw.head()

c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\wodyd\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,행정구역(시군구)별,연령별,2010.01,2010.01.1,2010.01.2,2011.01,2011.01.1,2011.01.2,2012.01,2012.01.1,...,2021.01.2,2022.01,2022.01.1,2022.01.2,2023.01,2023.01.1,2023.01.2,2024.01,2024.01.1,2024.01.2
0,행정구역(시군구)별,연령별,총인구수 (명),남자인구수 (명),여자인구수 (명),총인구수 (명),남자인구수 (명),여자인구수 (명),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,전국,계,49810609,24951327,24859282,50534731,25318961,25215770,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,0세,416297,214626,201671,446419,230193,216226,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1세,461758,237939,223819,442889,228288,214601,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2세,495767,254898,240869,463075,238573,224502,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. 장기요양 급여실적 파일 불러오기

In [8]:
ins_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\장기요양보험 지출 데이터"
ins_files = glob.glob(os.path.join(ins_path, "*.xlsx"))

print(f"현재 파일 수: {len(ins_files)}")
ins_files

현재 파일 수: 16

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\3-1_장기요양_급여현황_2015.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\3-2_ 장기요양_급여현황_2015.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2010.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2011.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2012.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2013.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2014.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2016.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2017.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2018.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2019.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2020.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2021.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2022.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2023.xlsx',
 'C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\장기요양보험 지출 데이터\\장기요양_급여현황_2024.xlsx']

### 2. 장기요양 급여실적 파일 합치기

In [13]:
ins_list = []
for f in ins_files:
    df1 = pd.read_excel(f)
    ins_list.append(df1)

ins_raw = pd.concat(ins_list, ignore_index=True)
ins_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,제 III편
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. 1인당 GRDP 파일 불러오기

In [10]:
GRPD_path = r"C:\Users\wodyd\Desktop\파이널프로젝트 자료\1인당 GRDP_시도 10~24"
GRPD_files = glob.glob(os.path.join(GRPD_path, "*.xlsx"))

print(f"현재 파일 수: {len(GRPD_files)}")
GRPD_files

현재 파일 수: 1

['C:\\Users\\wodyd\\Desktop\\파이널프로젝트 자료\\1인당 GRDP_시도 10~24\\1인당_GRDP_시도__20260220153413.xlsx']

AttributeError: 'list' object has no attribute 'columns'